
import Pathology from "@/component/pathology/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pathology",
  description: "Generated by create next app",
};

export default function page() {
    return <Pathology />
}