
import AdvancedPathology from "@/component/pathology/AdvancedPathology";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pathology",
  description: "Generated by create next app",
};

export default function page() {
    return <AdvancedPathology />
}