
import MasterySeries from "@/component/pathology/masterySeries/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mastery Series",
  description: "Generated by create next app",
};

export default function page() {
    return <MasterySeries />
}