"use client";
import MainAbout from "@/component/aboutUs/MainAbout";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "About Us",
//   description: "Generated by create next app",
// };

export default function page() {
    return <MainAbout />
}