
import HomePage from "@/component/home/page";
import Home from "@/component/home/sections/Home";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <HomePage/>
    </div>
  );
}