import MedicalExamDetail from "@/component/PGMedical IntreceExam/MedicalExamDetail";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Exam",
  description: "Generated by create next app",
};

export default function page() {
    return (
        <MedicalExamDetail />
    )
}