import PgMedicalEntranceExams from "@/component/PGMedical IntreceExam/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Exam",
  description: "Generated by create next app",
};

export default function page() {
    return (
        <PgMedicalEntranceExams />
    )
}