
import EditProfile from "@/component/editProfile/EditProfile";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Pathology",
    description: "Generated by create next app",
};

export default function page() {
    return <EditProfile />
}