
import HyperSpecialist from "@/component/pathology/HyperSpecialist/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hyper Specialist",
  description: "Generated by create next app",
};

export default function page() {
    return <HyperSpecialist />
}