// "use client";
import BlogCard from "@/component/blog/BlogCard";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};
export default function login() {
    return <BlogCard />
}