import RecordedPrograms from "@/component/pathology/sections/RecordedPrograms";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Recorded-programs",
    description: "Generated by create next app",
};

export default function page() {
    return <RecordedPrograms />
}